on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
    - master
name: validate
jobs:
  validate:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Setup dependencies
      run: |
        echo '{"w3capikey":"${{ secrets.W3C_API_KEY }}","ghToken":"${{ secrets.W3C_GITHUB_TOKEN }}"}' > config.json
        npm ci
    - name: Run validate.js
      run: node validate.js > report.json
    - name: Push report.json updates
      run: |
        git config user.name "w3c-validate-repos-bot"
        git config user.email "<>"
        git remote set-url --push origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
        git add report.json
        git commit -m "Update report.json"
        git show
        git push origin HEAD:master
